/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package si.rso.bicycle.schemas;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class EmailNotification extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7708942237917864374L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EmailNotification\",\"namespace\":\"si.rso.bicycle.schemas\",\"fields\":[{\"name\":\"data\",\"type\":{\"type\":\"map\",\"values\":\"string\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EmailNotification> ENCODER =
      new BinaryMessageEncoder<EmailNotification>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EmailNotification> DECODER =
      new BinaryMessageDecoder<EmailNotification>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<EmailNotification> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<EmailNotification> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EmailNotification>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this EmailNotification to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a EmailNotification from a ByteBuffer. */
  public static EmailNotification fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> data;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EmailNotification() {}

  /**
   * All-args constructor.
   * @param data The new value for data
   */
  public EmailNotification(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> data) {
    this.data = data;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return data;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: data = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'data' field.
   * @return The value of the 'data' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getData() {
    return data;
  }

  /**
   * Sets the value of the 'data' field.
   * @param value the value to set.
   */
  public void setData(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
    this.data = value;
  }

  /**
   * Creates a new EmailNotification RecordBuilder.
   * @return A new EmailNotification RecordBuilder
   */
  public static si.rso.bicycle.schemas.EmailNotification.Builder newBuilder() {
    return new si.rso.bicycle.schemas.EmailNotification.Builder();
  }

  /**
   * Creates a new EmailNotification RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EmailNotification RecordBuilder
   */
  public static si.rso.bicycle.schemas.EmailNotification.Builder newBuilder(si.rso.bicycle.schemas.EmailNotification.Builder other) {
    return new si.rso.bicycle.schemas.EmailNotification.Builder(other);
  }

  /**
   * Creates a new EmailNotification RecordBuilder by copying an existing EmailNotification instance.
   * @param other The existing instance to copy.
   * @return A new EmailNotification RecordBuilder
   */
  public static si.rso.bicycle.schemas.EmailNotification.Builder newBuilder(si.rso.bicycle.schemas.EmailNotification other) {
    return new si.rso.bicycle.schemas.EmailNotification.Builder(other);
  }

  /**
   * RecordBuilder for EmailNotification instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EmailNotification>
    implements org.apache.avro.data.RecordBuilder<EmailNotification> {

    private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> data;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(si.rso.bicycle.schemas.EmailNotification.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.data)) {
        this.data = data().deepCopy(fields()[0].schema(), other.data);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing EmailNotification instance
     * @param other The existing instance to copy.
     */
    private Builder(si.rso.bicycle.schemas.EmailNotification other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.data)) {
        this.data = data().deepCopy(fields()[0].schema(), other.data);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'data' field.
      * @return The value.
      */
    public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getData() {
      return data;
    }

    /**
      * Sets the value of the 'data' field.
      * @param value The value of 'data'.
      * @return This builder.
      */
    public si.rso.bicycle.schemas.EmailNotification.Builder setData(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
      validate(fields()[0], value);
      this.data = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'data' field has been set.
      * @return True if the 'data' field has been set, false otherwise.
      */
    public boolean hasData() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'data' field.
      * @return This builder.
      */
    public si.rso.bicycle.schemas.EmailNotification.Builder clearData() {
      data = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EmailNotification build() {
      try {
        EmailNotification record = new EmailNotification();
        record.data = fieldSetFlags()[0] ? this.data : (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EmailNotification>
    WRITER$ = (org.apache.avro.io.DatumWriter<EmailNotification>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EmailNotification>
    READER$ = (org.apache.avro.io.DatumReader<EmailNotification>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
