apiVersion: v1
kind: Service
metadata:
  name: billing
  namespace: bicycle
spec:
  selector:
    app: billing
  ports:
  - port: 80
    name: billing
    targetPort: billing
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: billing
  namespace: bicycle
spec:
  hosts:
  - "*"
  gateways:
  - api-ingress
  http:
  - match:
    - uri:
        prefix: /billing
    route:
    - destination:
        port:
          number: 80
        host: billing.bicycle.svc.cluster.local
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: billing
  namespace: bicycle
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: billing
    spec:
      imagePullSecrets:
      - name: docker-registry
      containers:
      - name: billing
        image: eu.gcr.io/rso-bicycle/billing:master
        imagePullPolicy: Always
        ports:
        - name: billing
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 3
        env:
        - name: PORT
          value: "8080"
        - name: KUMULUZEE_DATASOURCES0_JNDINAME
          value: "jdbc/billing"
        - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
          valueFrom:
            secretKeyRef:
              name: ibm-billing-db
              key: conn
        - name: KUMULUZEE_DATASOURCES0_USERNAME
          value: "admin"
        - name: KUMULUZEE_DATASOURCES0_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ibm-billing-db
              key: password